metadata: {}
pipelines:
  co2-emissions:
    envs:
    - host
    path: pipelines/co2-emissions
    stages:
    - setup
    - run
    - validate
  sea-surface-mapping:
    envs:
    - host
    path: pipelines/sea-surface-mapping
    stages:
    - setup.sh
    - run.sh
